
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FAETEC
 */
public class telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaprincipal
     */
    public telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g94rerss = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        txtPesoTerra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbUrano = new javax.swing.JRadioButton();
        rbMercurio = new javax.swing.JRadioButton();
        rbMarte = new javax.swing.JRadioButton();
        rbSaturno = new javax.swing.JRadioButton();
        rbJupiter = new javax.swing.JRadioButton();
        rbVenus = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("peso fora da terra");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        txtPesoTerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoTerraActionPerformed(evt);
            }
        });

        jLabel2.setText("Peso da Terra (KG): ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione o planeta:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        g94rerss.add(rbUrano);
        rbUrano.setText("Urano");
        rbUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUranoActionPerformed(evt);
            }
        });

        g94rerss.add(rbMercurio);
        rbMercurio.setText("Mercúrio");
        rbMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMercurioActionPerformed(evt);
            }
        });

        g94rerss.add(rbMarte);
        rbMarte.setText("Marte");

        g94rerss.add(rbSaturno);
        rbSaturno.setText("Saturno");
        rbSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSaturnoActionPerformed(evt);
            }
        });

        g94rerss.add(rbJupiter);
        rbJupiter.setText("Júpiter");
        rbJupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJupiterActionPerformed(evt);
            }
        });

        g94rerss.add(rbVenus);
        rbVenus.setText("Vênus");
        rbVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVenusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbUrano)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbMercurio, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rbMarte)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbVenus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbJupiter)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbSaturno)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbUrano)
                    .addComponent(rbJupiter))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbMercurio)
                    .addComponent(rbVenus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSaturno)
                    .addComponent(rbMarte))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton1.setMnemonic('C');
        jButton1.setText("Calcular novo peso");
        jButton1.setToolTipText("Clique para calcular seu peso em outro planeta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Limpar.setMnemonic('L');
        Limpar.setText("Limpar");
        Limpar.setToolTipText("Clique para limpar os campos");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        jButton3.setMnemonic('S');
        jButton3.setText("Sair");
        jButton3.setToolTipText("Clique para sair da aplicação");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesoTerra, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPesoTerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMercurioActionPerformed

    private void rbSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSaturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSaturnoActionPerformed

    private void rbVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVenusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        txtPesoTerra.setText(""); //limpa o valor do peso
        g94rerss.clearSelection(); //limpa a seleçao de planeta
        txtPesoTerra.requestFocus(); //posiciona o cursor no campo peso
        
    }//GEN-LAST:event_LimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double pesoTerra , pesoOutroPlaneta;
       pesoTerra=Double.parseDouble(txtPesoTerra.getText());
        if(rbMercurio.isSelected())
        {
            pesoOutroPlaneta=pesoTerra*0.37;
            JOptionPane.showMessageDialog(this, "Seu peso em Mercúrio é "+pesoOutroPlaneta+"Kg.","Resultado Final",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else if(rbVenus.isSelected())
        {
            pesoOutroPlaneta=pesoTerra*0.88;
            JOptionPane.showMessageDialog(this, "Seu peso em Vênus é "+pesoOutroPlaneta+"Kg.","Resultado Final",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else if(rbMarte.isSelected())
        {
            pesoOutroPlaneta=pesoTerra*0.38;
            JOptionPane.showMessageDialog(this, "Seu peso em Marte é "+pesoOutroPlaneta+"Kg.","Resultado Final",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else if(rbJupiter.isSelected())
        {
            pesoOutroPlaneta=pesoTerra*2.64;
            JOptionPane.showMessageDialog(this, "Seu peso em Júpiter é "+pesoOutroPlaneta+"Kg.","Resultado Final",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else if(rbSaturno.isSelected())
        {
            pesoOutroPlaneta=pesoTerra*1.15;
            JOptionPane.showMessageDialog(this, "Seu peso em Saturno é "+pesoOutroPlaneta+"Kg.","Resultado Final",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else if(rbUrano.isSelected())
        {
            pesoOutroPlaneta=pesoTerra*1.17;
            JOptionPane.showMessageDialog(this, "Seu peso em Urano é "+pesoOutroPlaneta+"Kg.","Resultado Final",JOptionPane.INFORMATION_MESSAGE);
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Selecione um planeta.","Erro",JOptionPane.INFORMATION_MESSAGE);
        
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesoTerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoTerraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoTerraActionPerformed

    private void rbUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbUranoActionPerformed

    private void rbJupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJupiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJupiterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.ButtonGroup g94rerss;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JRadioButton rbJupiter;
    private javax.swing.JRadioButton rbMarte;
    private javax.swing.JRadioButton rbMercurio;
    private javax.swing.JRadioButton rbSaturno;
    private javax.swing.JRadioButton rbUrano;
    private javax.swing.JRadioButton rbVenus;
    private javax.swing.JTextField txtPesoTerra;
    // End of variables declaration//GEN-END:variables
}
